// Contenido para: src/styles.ts
import type React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  loginContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', backgroundColor: '#f0f2f5', fontFamily: 'system-ui, sans-serif' },
  loginBox: { padding: '40px', backgroundColor: 'white', borderRadius: '12px', boxShadow: '0 8px 30px rgba(0, 0, 0, 0.1)', textAlign: 'center', width: '420px', display: 'flex', flexDirection: 'column', alignItems: 'center' },
  loginSubtitle: { margin: '10px 0 25px 0', fontSize: '16px', color: '#666' },
  loginInput: { width: '100%', boxSizing: 'border-box', padding: '12px 10px', marginBottom: '15px', border: '1px solid #ddd', borderRadius: '6px', fontSize: '14px' },
  loginButton: { width: '100%', padding: '12px', border: 'none', borderRadius: '6px', backgroundColor: '#007bff', color: 'white', fontSize: '16px', cursor: 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', transition: 'background-color 0.2s' },
  loginError: { color: '#dc3545', marginBottom: '15px', fontSize: '14px' },
  userSelectionContainer: { display: 'flex', justifyContent: 'center', gap: '20px', flexWrap: 'wrap', marginTop: '20px', },
  userProfile: { display: 'flex', flexDirection: 'column', alignItems: 'center', cursor: 'pointer', padding: '10px', borderRadius: '8px', transition: 'background-color 0.2s', width: '100px', },
  userAvatar: { width: '64px', height: '64px', borderRadius: '50%', backgroundColor: '#e9ecef', display: 'flex', justifyContent: 'center', alignItems: 'center', color: '#495057', marginBottom: '8px', },
  userName: { fontSize: '14px', fontWeight: '500', color: '#343a40', },
  selectedUserProfile: { display: 'flex', flexDirection: 'column', alignItems: 'center', marginBottom: '20px', },
  switchUserButton: { background: 'none', border: 'none', color: '#007bff', cursor: 'pointer', fontSize: '14px', marginTop: '15px', padding: '5px', },
  
  // --- INICIO DE CORRECCIÓN SCROLL (100vh -> 100%) ---
  appContainer: { display: 'flex', height: '100%', backgroundColor: '#f8f9fa', fontFamily: 'system-ui, sans-serif' },
  // --- FIN DE CORRECCIÓN SCROLL ---
  
  sidebar: { width: '260px', backgroundColor: '#ffffff', padding: '20px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', borderRight: '1px solid #e9ecef' },
  sidebarTitle: { fontSize: '12px', textTransform: 'uppercase', letterSpacing: '1px', color: '#6c757d', padding: '0 15px', marginBottom: '10px', fontWeight: '600' },
  sidebarButton: { display: 'flex', alignItems: 'center', width: '100%', padding: '12px 15px', border: 'none', backgroundColor: 'transparent', textAlign: 'left', fontSize: '15px', color: '#495057', borderRadius: '8px', cursor: 'pointer', marginBottom: '5px', transition: 'background-color 0.2s, color 0.2s' },
  sidebarButtonActive: { backgroundColor: '#e9f3ff', color: '#007bff', fontWeight: '600' },
  currentUserInfo: { padding: '10px 15px', fontSize: '14px', color: '#495057', textAlign: 'center', borderTop: '1px solid #e9ecef', marginTop: '10px' },
  sidebarFooter: { padding: '15px', fontSize: '12px', color: '#6c757d', textAlign: 'center', borderTop: '1px solid #e9ecef', marginTop: '10px' },
  
  // --- INICIO CORRECCIÓN ESTILO BOTÓN LOGOUT (para el header) ---
  logoutButton: { 
    padding: '10px 15px', 
    border: 'none', 
    borderRadius: '6px', 
    backgroundColor: '#dc3545', 
    color: 'white', 
    fontSize: '14px', 
    cursor: 'pointer', 
    display: 'flex', 
    alignItems: 'center', 
    fontWeight: '500', 
    transition: 'background-color 0.2s' 
  },
  // --- FIN CORRECCIÓN ESTILO BOTÓN LOGOUT ---

  mainContent: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  header: { padding: '20px 30px', borderBottom: '1px solid #e9ecef', display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#ffffff', flexShrink: 0 },
  headerTitle: { margin: 0, fontSize: '28px', color: '#212529', fontWeight: '700' },
  actionButton: { padding: '10px 15px', border: 'none', borderRadius: '6px', backgroundColor: '#007bff', color: 'white', fontSize: '14px', cursor: 'pointer', display: 'flex', alignItems: 'center', fontWeight: '500', transition: 'background-color 0.2s' },
  contentArea: { padding: '30px', overflowY: 'auto', flex: 1 },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '30px' },
  card: { backgroundColor: 'white', padding: '25px', borderRadius: '12px', boxShadow: '0 2px 10px rgba(0,0,0,0.05)' },
  cardTitle: { marginTop: 0, marginBottom: '20px', fontSize: '20px', color: '#343a40', fontWeight: '600' },
  listContainer: { maxHeight: 'calc(100vh - 280px)', overflowY: 'auto' },
  listContainerSmall: { maxHeight: '150px', overflowY: 'auto', border: '1px solid #eee', borderRadius: '8px', padding: '10px' },
  listItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 5px', borderBottom: '1px solid #f1f3f5' },
  listItemName: { margin: 0, fontWeight: '500', color: '#343a40' },
  listItemInfo: { margin: '4px 0 0 0', fontSize: '14px', color: '#6c757d' },
  pillSuccess: { backgroundColor: 'rgba(40, 167, 69, 0.1)', color: '#155724', padding: '5px 12px', borderRadius: '12px', fontSize: '12px', fontWeight: '600' },
  pillWarning: { backgroundColor: 'rgba(255, 193, 7, 0.1)', color: '#856404', padding: '5px 12px', borderRadius: '12px', fontSize: '12px', fontWeight: '600' },
  pillInfo: { backgroundColor: 'rgba(0, 123, 255, 0.1)', color: '#004085', padding: '6px 14px', borderRadius: '8px', fontSize: '13px', fontWeight: '600', border: 'none', cursor: 'pointer' },
  formGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px', marginBottom: '15px' },
  formInput: { display: 'block', width: '100%', boxSizing: 'border-box', padding: '12px 10px', border: '1px solid #ddd', borderRadius: '6px', fontSize: '14px', marginBottom: '10px' },
  checkboxLabel: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px' },
  submitButton: { width: '100%', padding: '12px', border: 'none', borderRadius: '6px', backgroundColor: '#007bff', color: 'white', fontSize: '16px', cursor: 'pointer', marginTop: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  deleteButton: { backgroundColor: 'rgba(220, 53, 69, 0.1)', color: '#dc3545', border: 'none', borderRadius: '50%', width: '30px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  modalBackdrop: { position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modalContent: { backgroundColor: 'white', padding: '30px', borderRadius: '12px', width: '90%', maxWidth: '700px', boxShadow: '0 5px 15px rgba(0,0,0,0.3)', position: 'relative' },
  modalGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', rowGap: '5px' },
  modalCloseButton: { background: 'transparent', border: 'none', cursor: 'pointer' },
  modalSection: { marginBottom: '10px' },
  modalSectionTitle: { borderBottom: '1px solid #eee', paddingBottom: '8px', marginBottom: '12px', fontSize: '16px', color: '#343a40' },
  subListItem: { fontSize: '14px', color: '#495057', padding: '8px 5px', borderBottom: '1px solid #f1f3f5' },
  calendarHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap' },
  calendarNavButton: { background: 'transparent', border: 'none', cursor: 'pointer', padding: '5px' },
  calendarGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '5px' },
  weekDay: { fontWeight: '600', textAlign: 'center', fontSize: '12px', color: '#6c757d', paddingBottom: '10px' },
  dayCell: { border: '1px solid #f1f3f5', borderRadius: '4px', minHeight: '100px', padding: '5px', transition: 'background-color 0.3s' },
  dayCellEmpty: { border: '1px solid transparent' },
  dayNumber: { fontSize: '12px', fontWeight: '500' },
  dayCount: { display: 'flex', alignItems: 'center', justifyContent: 'center', marginTop: '10px', fontSize: '16px', color: '#343a40', fontWeight: '600' },
  eventsContainer: { marginTop: '5px', display: 'flex', flexDirection: 'column', gap: '4px' },
  eventPill: { padding: '3px 6px', borderRadius: '4px', fontSize: '11px', backgroundColor: '#e9f3ff', color: '#004085', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  penaltyPill: { padding: '3px 6px', borderRadius: '4px', fontSize: '11px', backgroundColor: '#fff3cd', color: '#856404', marginTop: '4px', display: 'flex', alignItems: 'center' },
  attendancePill: { padding: '3px 6px', borderRadius: '4px', fontSize: '11px', backgroundColor: '#e9f3ff', color: '#004085' },
  attendanceItem: { padding: '15px 5px', borderBottom: '1px solid #f1f3f5' },
  attendanceGrid: { display: 'grid', gridTemplateColumns: '1fr 1.5fr 1fr 1.5fr auto', gap: '10px', alignItems: 'center', marginTop: '10px' },
  formInputSmall: { width: '100%', boxSizing: 'border-box', padding: '8px', border: '1px solid #ddd', borderRadius: '6px', fontSize: '14px' },
  saveButton: { backgroundColor: '#28a745', color: 'white', border: 'none', borderRadius: '6px', padding: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  dashboardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px' },
  statCard: { backgroundColor: 'white', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 10px rgba(0,0,0,0.05)', display: 'flex', alignItems: 'center', gap: '20px' },
  chartContainer: { position: 'relative', height: '300px', width: '100%' },
  notificationContainer: { position: 'fixed', top: '20px', right: '20px', zIndex: 2000, display: 'flex', flexDirection: 'column', gap: '10px' },
  notification: { backgroundColor: '#28a745', color: 'white', padding: '15px', borderRadius: '8px', boxShadow: '0 4px 12px rgba(0,0,0,0.15)', animation: 'fadeIn 0.5s, fadeOut 0.5s 2.5s' },
  formLabel: { display: 'block', fontSize: '14px', fontWeight: '500', marginBottom: '5px', color: '#495057' },
  uploadButton: { backgroundColor: '#17a2b8', color: 'white', padding: '10px 15px', borderRadius: '6px', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', fontSize: '14px' },
    loadingContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
        fontFamily: 'system-ui, sans-serif',
        color: '#495057'
    },
    spinner: {
        border: '4px solid #f3f3f3',
        borderTop: '4px solid #007bff',
        borderRadius: '50%',
        width: '40px',
        height: '40px',
        animation: 'spin 1s linear infinite',
        marginBottom: '20px'
    },
    statCardText: { margin: 0, color: '#6c757d', fontSize: '14px' },
    statCardNumber: { color: '#212529', fontSize: '22px', fontWeight: '600' }
};